# Generated by Django 6.0.3 on 2026-03-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_alter_workorder_wo_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('WO_OPENED', 'Work Order Opened'), ('STEP_ADDED', 'Step Added'), ('STEP_DONE', 'Step Done'), ('INSPECTION_RECORDED', 'Inspection Recorded'), ('WO_CLOSED', 'Work Order Closed')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(default='system', max_length=100)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workorders.workorder')),
            ],
        ),
    ]
