# Generated by Django 6.0.3 on 2026-03-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event',
            field=models.CharField(choices=[('WO_OPENED', 'Work Order Opened'), ('WO_CLOSED', 'Work Order Closed'), ('STEP_ADDED', 'Step Added'), ('STEP_DONE', 'Step Done'), ('STEP_DELETED', 'Step Deleted'), ('INSPECTION_RECORDED', 'Inspection Recorded'), ('INSPECTION_DELETED', 'Inspection Deleted')], max_length=50),
        ),
    ]
